2025-10-31T06:50:57.606505876Z npm error ./src/util/custom-aggregate.lzz:99:59: error: ‘start’ was not declared in this scope
2025-10-31T06:50:57.606507997Z npm error ./src/util/custom-aggregate.lzz: In static member function ‘static void CustomAggregate::DestroyAccumulator(sqlite3_context*)’:
2025-10-31T06:50:57.606510067Z npm error ./src/util/custom-aggregate.lzz:108:22: error: ‘struct CustomAggregate::Accumulator’ has no member named ‘value’
2025-10-31T06:50:57.606512147Z npm error ./src/util/custom-table.lzz: In constructor ‘CustomTable::CustomTable(v8::Isolate*, Database*, const char*, v8::Local<v8::Function>)’:
2025-10-31T06:50:57.606517667Z npm error ./src/util/custom-table.lzz:9:70: error: class ‘CustomTable’ does not have any field named ‘factory’
2025-10-31T06:50:57.606519857Z npm error ./src/util/custom-table.lzz: At global scope:
2025-10-31T06:50:57.606522978Z npm error ./src/util/custom-table.lzz:45:9: warning: missing initializer for member ‘sqlite3_module::xIntegrity’ [-Wmissing-field-initializers]
2025-10-31T06:50:57.606525168Z npm error ./src/util/custom-table.lzz:72:9: warning: missing initializer for member ‘sqlite3_module::xIntegrity’ [-Wmissing-field-initializers]
2025-10-31T06:50:57.606527278Z npm error ./src/util/custom-table.lzz: In constructor ‘CustomTable::VTab::VTab(CustomTable*, v8::Local<v8::Function>, std::vector<std::__cxx11::basic_string<char> >, bool)’:
2025-10-31T06:50:57.606529468Z npm error ./src/util/custom-table.lzz:83:87: error: class ‘CustomTable::VTab’ does not have any field named ‘generator’
2025-10-31T06:50:57.606533829Z npm error ./src/util/custom-table.lzz: In static member function ‘static int CustomTable::xConnect(sqlite3*, void*, int, const char* const*, sqlite3_vtab**, char**)’:
2025-10-31T06:50:57.606535959Z npm error ./src/util/custom-table.lzz:164:70: error: no match for ‘operator=’ (operand types are ‘v8::Local<v8::Value>’ and ‘v8::Local<v8::String>’)
2025-10-31T06:50:57.606538169Z npm error /opt/render/.cache/25.1.0/include/node/v8-local-handle.h:360:22: note: candidate: ‘constexpr v8::Local<v8::Value>& v8::Local<v8::Value>::operator=(const v8::Local<v8::Value>&)’
2025-10-31T06:50:57.606540279Z npm error   360 | class V8_TRIVIAL_ABI Local : public LocalBase<T>,
2025-10-31T06:50:57.606542699Z npm error       |                      ^~~~~
2025-10-31T06:50:57.60654487Z npm error /opt/render/.cache/25.1.0/include/node/v8-local-handle.h:360:22: note:   no known conversion for argument 1 from ‘v8::Local<v8::String>’ to ‘const v8::Local<v8::Value>&’
2025-10-31T06:50:57.606547Z npm error /opt/render/.cache/25.1.0/include/node/v8-local-handle.h:360:22: note: candidate: ‘constexpr v8::Local<v8::Value>& v8::Local<v8::Value>::operator=(v8::Local<v8::Value>&&)’
2025-10-31T06:50:57.60654915Z npm error /opt/render/.cache/25.1.0/include/node/v8-local-handle.h:360:22: note:   no known conversion for argument 1 from ‘v8::Local<v8::String>’ to ‘v8::Local<v8::Value>&&’
2025-10-31T06:50:57.60655126Z npm error ./src/util/custom-table.lzz:168:68: error: ‘class CustomTable’ has no member named ‘factory’
2025-10-31T06:50:57.60655346Z npm error ./src/util/custom-table.lzz:184:61: error: no matching function for call to ‘v8::String::Utf8Value::Utf8Value(v8::Isolate*&, v8::Local<v8::String>&)’
2025-10-31T06:50:57.606555671Z npm error /opt/render/.cache/25.1.0/include/node/v8-primitive.h:649:5: note: candidate: ‘v8::String::Utf8Value::Utf8Value(v8::Isolate*, v8::Local<v8::Value>)’
2025-10-31T06:50:57.606557751Z npm error   649 |     Utf8Value(Isolate* isolate, Local<v8::Value> obj);
2025-10-31T06:50:57.606559841Z npm error       |     ^~~~~~~~~
2025-10-31T06:50:57.606561971Z npm error /opt/render/.cache/25.1.0/include/node/v8-primitive.h:649:50: note:   no known conversion for argument 2 from ‘Local<v8::String>’ to ‘Local<v8::Value>’
2025-10-31T06:50:57.606564101Z npm error   649 |     Utf8Value(Isolate* isolate, Local<v8::Value> obj);
2025-10-31T06:50:57.606566201Z npm error       |                                 ~~~~~~~~~~~~~~~~~^~~
2025-10-31T06:50:57.606568381Z npm error ./src/util/custom-table.lzz:191:84: error: no matching function for call to ‘v8::String::Utf8Value::Utf8Value(v8::Isolate*&, v8::Local<v8::String>&)’
2025-10-31T06:50:57.606570612Z npm error /opt/render/.cache/25.1.0/include/node/v8-primitive.h:649:5: note: candidate: ‘v8::String::Utf8Value::Utf8Value(v8::Isolate*, v8::Local<v8::Value>)’
2025-10-31T06:50:57.606576552Z npm error   649 |     Utf8Value(Isolate* isolate, Local<v8::Value> obj);
2025-10-31T06:50:57.606578722Z npm error       |     ^~~~~~~~~
2025-10-31T06:50:57.606580902Z npm error /opt/render/.cache/25.1.0/include/node/v8-primitive.h:649:50: note:   no known conversion for argument 2 from ‘Local<v8::String>’ to ‘Local<v8::Value>’
2025-10-31T06:50:57.606587823Z npm error   649 |     Utf8Value(Isolate* isolate, Local<v8::Value> obj);
2025-10-31T06:50:57.606590093Z npm error       |                                 ~~~~~~~~~~~~~~~~~^~~
2025-10-31T06:50:57.606592203Z npm error ./src/util/custom-table.lzz: In static member function ‘static int CustomTable::xFilter(sqlite3_vtab_cursor*, int, const char*, int, sqlite3_value**)’:
2025-10-31T06:50:57.606594323Z npm error ./src/util/custom-table.lzz:257:72: error: no match for ‘operator=’ (operand types are ‘v8::Local<v8::Value>’ and ‘v8::Local<v8::Primitive>’)
2025-10-31T06:50:57.606596474Z npm error /opt/render/.cache/25.1.0/include/node/v8-local-handle.h:360:22: note: candidate: ‘constexpr v8::Local<v8::Value>& v8::Local<v8::Value>::operator=(const v8::Local<v8::Value>&)’
2025-10-31T06:50:57.606598654Z npm error   360 | class V8_TRIVIAL_ABI Local : public LocalBase<T>,
2025-10-31T06:50:57.606600734Z npm error       |                      ^~~~~
2025-10-31T06:50:57.606602824Z npm error /opt/render/.cache/25.1.0/include/node/v8-local-handle.h:360:22: note:   no known conversion for argument 1 from ‘v8::Local<v8::Primitive>’ to ‘const v8::Local<v8::Value>&’
2025-10-31T06:50:57.606604935Z npm error /opt/render/.cache/25.1.0/include/node/v8-local-handle.h:360:22: note: candidate: ‘constexpr v8::Local<v8::Value>& v8::Local<v8::Value>::operator=(v8::Local<v8::Value>&&)’
2025-10-31T06:50:57.606606995Z npm error /opt/render/.cache/25.1.0/include/node/v8-local-handle.h:360:22: note:   no known conversion for argument 1 from ‘v8::Local<v8::Primitive>’ to ‘v8::Local<v8::Value>&&’
2025-10-31T06:50:57.606609125Z npm error ./src/util/custom-table.lzz:263:65: error: ‘class CustomTable::VTab’ has no member named ‘generator’
2025-10-31T06:50:57.606611195Z npm error ./src/util/custom-table.lzz:273:77: error: ‘class CS’ has no member named ‘next’
2025-10-31T06:50:57.606613335Z npm error ./src/util/custom-table.lzz:273:128: error: expected primary-expression before ‘>’ token
2025-10-31T06:50:57.606616225Z npm error ./src/util/custom-table.lzz:273:130: error: expected primary-expression before ‘)’ token
2025-10-31T06:50:57.606618376Z npm error ./src/util/custom-table.lzz:274:25: error: ‘class CustomTable::Cursor’ has no member named ‘iterator’
2025-10-31T06:50:57.606620486Z npm error ./src/util/custom-table.lzz:275:25: error: ‘class CustomTable::Cursor’ has no member named ‘next’
2025-10-31T06:50:57.606622566Z npm error ./src/util/custom-table.lzz: In static member function ‘static int CustomTable::xNext(sqlite3_vtab_cursor*)’:
2025-10-31T06:50:57.606624636Z npm error ./src/util/custom-table.lzz:292:58: error: ‘class CustomTable::Cursor’ has no member named ‘iterator’
2025-10-31T06:50:57.606626796Z npm error ./src/util/custom-table.lzz:293:56: error: ‘class CustomTable::Cursor’ has no member named ‘next’
2025-10-31T06:50:57.606628896Z npm error ./src/util/custom-table.lzz:295:67: error: no matching function for call to ‘v8::Function::Call(v8::Local<v8::Context>&, v8::Local<v8::Object>&, int, NULL)’
2025-10-31T06:50:57.606631046Z npm error /opt/render/.cache/25.1.0/include/node/v8-function.h:56:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Function::Call(v8::Isolate*, v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*)’
2025-10-31T06:50:57.606636497Z npm error    56 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Call(v8::Isolate* isolate,
2025-10-31T06:50:57.606639277Z npm error       |                                           ^~~~
2025-10-31T06:50:57.606641397Z npm error /opt/render/.cache/25.1.0/include/node/v8-function.h:56:43: note:   candidate expects 5 arguments, 4 provided
2025-10-31T06:50:57.606644458Z npm error /opt/render/.cache/25.1.0/include/node/v8-function.h:60:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*)’
2025-10-31T06:50:57.606646588Z npm error    60 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Call(Local<Context> context,
2025-10-31T06:50:57.606648628Z npm error       |                                           ^~~~
2025-10-31T06:50:57.606650298Z npm error /opt/render/.cache/25.1.0/include/node/v8-function.h:61:61: note:   no known conversion for argument 2 from ‘Local<v8::Object>’ to ‘Local<v8::Value>’
2025-10-31T06:50:57.606652008Z npm error    61 |                                                Local<Value> recv, int argc,
2025-10-31T06:50:57.606653988Z npm error       |                                                ~~~~~~~~~~~~~^~~~
2025-10-31T06:50:57.606655919Z npm error ./src/util/custom-table.lzz:302:56: error: ‘class CS’ has no member named ‘done’
2025-10-31T06:50:57.606657689Z npm error ./src/util/custom-table.lzz:302:106: error: expected primary-expression before ‘>’ token
2025-10-31T06:50:57.606659359Z npm error ./src/util/custom-table.lzz:302:108: error: expected primary-expression before ‘)’ token
2025-10-31T06:50:57.606664859Z npm error ./src/util/custom-table.lzz:304:33: error: ‘class CustomTable::Cursor’ has no member named ‘row’; did you mean ‘rowid’?
2025-10-31T06:50:57.606666659Z npm error ./src/util/custom-table.lzz:304:79: error: ‘class CS’ has no member named ‘value’
2025-10-31T06:50:57.60666836Z npm error ./src/util/custom-table.lzz:304:128: error: expected primary-expression before ‘>’ token
2025-10-31T06:50:57.60667008Z npm error ./src/util/custom-table.lzz:304:130: error: expected primary-expression before ‘)’ token
2025-10-31T06:50:57.60667176Z npm error ./src/util/custom-table.lzz: In static member function ‘static int CustomTable::xColumn(sqlite3_vtab_cursor*, sqlite3_context*, int)’:
2025-10-31T06:50:57.60667345Z npm error ./src/util/custom-table.lzz:325:52: error: ‘class CustomTable::Cursor’ has no member named ‘row’; did you mean ‘rowid’?
2025-10-31T06:50:57.60667518Z npm error ./src/util/data.lzz: In function ‘v8::Local<v8::Value> Data::GetValueJS(v8::Isolate*, sqlite3_stmt*, int, bool)’:
2025-10-31T06:50:57.60667738Z npm error ./src/util/data.lzz:73:138: error: could not convert ‘v8::BigInt::New(isolate, ((int64_t)sqlite3_column_int64(handle, column)))’ from ‘Local<v8::BigInt>’ to ‘Local<v8::Value>’
2025-10-31T06:50:57.606679441Z npm error ./src/util/data.lzz:73:244: error: could not convert ‘v8::Number::New(isolate, sqlite3_column_double(handle, column))’ from ‘Local<v8::Number>’ to ‘Local<v8::Value>’
2025-10-31T06:50:57.60668119Z npm error ./src/util/data.lzz:73:343: error: could not convert ‘StringFromUtf8(isolate, ((const char*)sqlite3_column_text(handle, column)), sqlite3_column_bytes(handle, column))’ from ‘Local<v8::String>’ to ‘Local<v8::Value>’
2025-10-31T06:50:57.606684191Z npm error ./src/util/data.lzz:73:676: error: could not convert ‘node::Buffer::Copy(isolate, ((const char*)sqlite3_column_blob(handle, column)), ((size_t)sqlite3_column_bytes(handle, column))).v8::MaybeLocal<v8::Object>::ToLocalChecked()’ from ‘Local<v8::Object>’ to ‘Local<v8::Value>’
2025-10-31T06:50:57.606685991Z npm error ./src/util/data.lzz:73:778: error: could not convert ‘v8::Null(isolate)’ from ‘Local<v8::Primitive>’ to ‘Local<v8::Value>’
2025-10-31T06:50:57.606690421Z npm error ./src/util/data.lzz: In function ‘v8::Local<v8::Value> Data::GetValueJS(v8::Isolate*, sqlite3_value*, bool)’:
2025-10-31T06:50:57.606692162Z npm error ./src/util/data.lzz:77:127: error: could not convert ‘v8::BigInt::New(isolate, ((int64_t)sqlite3_value_int64(value)))’ from ‘Local<v8::BigInt>’ to ‘Local<v8::Value>’
2025-10-31T06:50:57.606693882Z npm error ./src/util/data.lzz:77:222: error: could not convert ‘v8::Number::New(isolate, sqlite3_value_double(value))’ from ‘Local<v8::Number>’ to ‘Local<v8::Value>’
2025-10-31T06:50:57.606695552Z npm error ./src/util/data.lzz:77:310: error: could not convert ‘StringFromUtf8(isolate, ((const char*)sqlite3_value_text(value)), sqlite3_value_bytes(value))’ from ‘Local<v8::String>’ to ‘Local<v8::Value>’
2025-10-31T06:50:57.606697622Z npm error ./src/util/data.lzz:77:599: error: could not convert ‘node::Buffer::Copy(isolate, ((const char*)sqlite3_value_blob(value)), ((size_t)sqlite3_value_bytes(value))).v8::MaybeLocal<v8::Object>::ToLocalChecked()’ from ‘Local<v8::Object>’ to ‘Local<v8::Value>’
2025-10-31T06:50:57.606699322Z npm error ./src/util/data.lzz:77:690: error: could not convert ‘v8::Null(isolate)’ from ‘Local<v8::Primitive>’ to ‘Local<v8::Value>’
2025-10-31T06:50:57.606701062Z npm error ./src/util/data.lzz: In function ‘v8::Local<v8::Value> Data::GetFlatRowJS(v8::Isolate*, v8::Local<v8::Context>, sqlite3_stmt*, bool)’:
2025-10-31T06:50:57.606702722Z npm error ./src/util/data.lzz:84:33: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::Context>&, v8::Local<v8::String>, v8::Local<v8::Value>)’
2025-10-31T06:50:57.606704392Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:249:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
2025-10-31T06:50:57.606706052Z npm error   249 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
2025-10-31T06:50:57.606707743Z npm error       |                                     ^~~
2025-10-31T06:50:57.606709413Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:250:54: note:   no known conversion for argument 2 from ‘Local<v8::String>’ to ‘Local<v8::Value>’
2025-10-31T06:50:57.606711113Z npm error   250 |                                         Local<Value> key, Local<Value> value);
2025-10-31T06:50:57.606712823Z npm error       |                                         ~~~~~~~~~~~~~^~~
2025-10-31T06:50:57.606718444Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:251:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::MaybeLocal<v8::Object>)’
2025-10-31T06:50:57.606720304Z npm error   251 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
2025-10-31T06:50:57.606721974Z npm error       |                                     ^~~
2025-10-31T06:50:57.606723614Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:251:37: note:   candidate expects 4 arguments, 3 provided
2025-10-31T06:50:57.606725344Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:255:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
2025-10-31T06:50:57.606727004Z npm error   255 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
2025-10-31T06:50:57.606728734Z npm error       |                                     ^~~
2025-10-31T06:50:57.606730465Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:255:74: note:   no known conversion for argument 2 from ‘v8::Local<v8::String>’ to ‘uint32_t’ {aka ‘unsigned int’}
2025-10-31T06:50:57.606734735Z npm error   255 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
2025-10-31T06:50:57.606736495Z npm error       |                                                                 ~~~~~~~~~^~~~~
2025-10-31T06:50:57.606738155Z npm error ./src/util/data.lzz:88:24: error: could not convert ‘row’ from ‘Local<v8::Object>’ to ‘Local<v8::Value>’
2025-10-31T06:50:57.606739845Z npm error ./src/util/data.lzz: In function ‘v8::Local<v8::Value> Data::GetExpandedRowJS(v8::Isolate*, v8::Local<v8::Context>, sqlite3_stmt*, bool)’:
2025-10-31T06:50:57.606741575Z npm error ./src/util/data.lzz:99:48: error: no matching function for call to ‘v8::Object::HasOwnProperty(v8::Local<v8::Context>&, v8::Local<v8::String>&)’
2025-10-31T06:50:57.606743315Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:677:37: note: candidate: ‘v8::Maybe<bool> v8::Object::HasOwnProperty(v8::Local<v8::Context>, v8::Local<v8::Name>)’
2025-10-31T06:50:57.606745076Z npm error   677 |   V8_WARN_UNUSED_RESULT Maybe<bool> HasOwnProperty(Local<Context> context,
2025-10-31T06:50:57.606748126Z npm error       |                                     ^~~~~~~~~~~~~~
2025-10-31T06:50:57.606749896Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:678:64: note:   no known conversion for argument 2 from ‘Local<v8::String>’ to ‘Local<v8::Name>’
2025-10-31T06:50:57.606751656Z npm error   678 |                                                    Local<Name> key);
2025-10-31T06:50:57.606753456Z npm error       |                                                    ~~~~~~~~~~~~^~~
2025-10-31T06:50:57.606755127Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:679:37: note: candidate: ‘v8::Maybe<bool> v8::Object::HasOwnProperty(v8::Local<v8::Context>, uint32_t)’
2025-10-31T06:50:57.606756887Z npm error   679 |   V8_WARN_UNUSED_RESULT Maybe<bool> HasOwnProperty(Local<Context> context,
2025-10-31T06:50:57.606758587Z npm error       |                                     ^~~~~~~~~~~~~~
2025-10-31T06:50:57.606760297Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:680:61: note:   no known conversion for argument 2 from ‘v8::Local<v8::String>’ to ‘uint32_t’ {aka ‘unsigned int’}
2025-10-31T06:50:57.606761977Z npm error   680 |                                                    uint32_t index);
2025-10-31T06:50:57.606763627Z npm error       |                                                    ~~~~~~~~~^~~~~
2025-10-31T06:50:57.606765367Z npm error ./src/util/data.lzz:100:41: error: no matching function for call to ‘v8::Object::Get(v8::Local<v8::Context>&, v8::Local<v8::String>&)’
2025-10-31T06:50:57.606767057Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:307:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)’
2025-10-31T06:50:57.606768798Z npm error   307 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
2025-10-31T06:50:57.606770538Z npm error       |                                           ^~~
2025-10-31T06:50:57.606772268Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:308:60: note:   no known conversion for argument 2 from ‘Local<v8::String>’ to ‘Local<v8::Value>’
2025-10-31T06:50:57.606773968Z npm error   308 |                                               Local<Value> key);
2025-10-31T06:50:57.606775668Z npm error       |                                               ~~~~~~~~~~~~~^~~
2025-10-31T06:50:57.606777348Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:309:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::MaybeLocal<v8::Object>)’
2025-10-31T06:50:57.606782929Z npm error   309 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
2025-10-31T06:50:57.606786919Z npm error       |                                           ^~~
2025-10-31T06:50:57.606788679Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:309:43: note:   candidate expects 3 arguments, 2 provided
2025-10-31T06:50:57.606790339Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:313:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)’
2025-10-31T06:50:57.60679203Z npm error   313 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
2025-10-31T06:50:57.60679375Z npm error       |                                           ^~~
2025-10-31T06:50:57.60679549Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:314:56: note:   no known conversion for argument 2 from ‘v8::Local<v8::String>’ to ‘uint32_t’ {aka ‘unsigned int’}
2025-10-31T06:50:57.60679743Z npm error   314 |                                               uint32_t index);
2025-10-31T06:50:57.60679912Z npm error       |                                               ~~~~~~~~~^~~~~
2025-10-31T06:50:57.60680079Z npm error ./src/util/data.lzz:100:84: error: expected primary-expression before ‘>’ token
2025-10-31T06:50:57.60680247Z npm error ./src/util/data.lzz:100:86: error: expected primary-expression before ‘)’ token
2025-10-31T06:50:57.606804191Z npm error ./src/util/data.lzz:103:41: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::Context>&, v8::Local<v8::String>&, v8::Local<v8::Object>&)’
2025-10-31T06:50:57.606805911Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:249:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
2025-10-31T06:50:57.606807621Z npm error   249 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
2025-10-31T06:50:57.606809321Z npm error       |                                     ^~~
2025-10-31T06:50:57.606811101Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:250:54: note:   no known conversion for argument 2 from ‘Local<v8::String>’ to ‘Local<v8::Value>’
2025-10-31T06:50:57.606812841Z npm error   250 |                                         Local<Value> key, Local<Value> value);
2025-10-31T06:50:57.606814521Z npm error       |                                         ~~~~~~~~~~~~~^~~
2025-10-31T06:50:57.606816201Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:251:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::MaybeLocal<v8::Object>)’
2025-10-31T06:50:57.606817901Z npm error   251 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
2025-10-31T06:50:57.606819572Z npm error       |                                     ^~~
2025-10-31T06:50:57.606821262Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:251:37: note:   candidate expects 4 arguments, 3 provided
2025-10-31T06:50:57.606822962Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:255:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
2025-10-31T06:50:57.606824662Z npm error   255 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
2025-10-31T06:50:57.606826332Z npm error       |                                     ^~~
2025-10-31T06:50:57.606855955Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:255:74: note:   no known conversion for argument 2 from ‘v8::Local<v8::String>’ to ‘uint32_t’ {aka ‘unsigned int’}
2025-10-31T06:50:57.606859055Z npm error   255 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
2025-10-31T06:50:57.606866265Z npm error       |                                                                 ~~~~~~~~~^~~~~
2025-10-31T06:50:57.606868956Z npm error ./src/util/data.lzz:104:44: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::Context>&, v8::Local<v8::String>&, v8::Local<v8::Value>&)’
2025-10-31T06:50:57.606871706Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:249:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
2025-10-31T06:50:57.606874446Z npm error   249 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
2025-10-31T06:50:57.606877116Z npm error       |                                     ^~~
2025-10-31T06:50:57.606879897Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:250:54: note:   no known conversion for argument 2 from ‘Local<v8::String>’ to ‘Local<v8::Value>’
2025-10-31T06:50:57.606882497Z npm error   250 |                                         Local<Value> key, Local<Value> value);
2025-10-31T06:50:57.606884167Z npm error       |                                         ~~~~~~~~~~~~~^~~
2025-10-31T06:50:57.606898188Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:251:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::MaybeLocal<v8::Object>)’
2025-10-31T06:50:57.606900178Z npm error   251 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
2025-10-31T06:50:57.606901868Z npm error       |                                     ^~~
2025-10-31T06:50:57.606905759Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:251:37: note:   candidate expects 4 arguments, 3 provided
2025-10-31T06:50:57.606907499Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:255:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
2025-10-31T06:50:57.606909209Z npm error   255 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
2025-10-31T06:50:57.606910859Z npm error       |                                     ^~~
2025-10-31T06:50:57.606912529Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:255:74: note:   no known conversion for argument 2 from ‘v8::Local<v8::String>’ to ‘uint32_t’ {aka ‘unsigned int’}
2025-10-31T06:50:57.606914259Z npm error   255 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
2025-10-31T06:50:57.60691598Z npm error       |                                                                 ~~~~~~~~~^~~~~
2025-10-31T06:50:57.60691771Z npm error ./src/util/data.lzz:107:24: error: could not convert ‘row’ from ‘Local<v8::Object>’ to ‘Local<v8::Value>’
2025-10-31T06:50:57.60691943Z npm error ./src/util/data.lzz: In function ‘v8::Local<v8::Value> Data::GetRawRowJS(v8::Isolate*, v8::Local<v8::Context>, sqlite3_stmt*, bool)’:
2025-10-31T06:50:57.60692109Z npm error ./src/util/data.lzz:116:24: error: could not convert ‘row’ from ‘Local<v8::Array>’ to ‘Local<v8::Value>’
2025-10-31T06:50:57.60692281Z npm error ./src/util/data.lzz: In function ‘int Data::BindValueFromJS(v8::Isolate*, sqlite3_stmt*, int, v8::Local<v8::Value>)’:
2025-10-31T06:50:57.60692453Z npm error ./src/util/data.lzz:136:456: error: no matching function for call to ‘v8::String::Utf8Value::Utf8Value(v8::Isolate*&, v8::Local<v8::String>)’
2025-10-31T06:50:57.60692628Z npm error /opt/render/.cache/25.1.0/include/node/v8-primitive.h:649:5: note: candidate: ‘v8::String::Utf8Value::Utf8Value(v8::Isolate*, v8::Local<v8::Value>)’
2025-10-31T06:50:57.606927981Z npm error   649 |     Utf8Value(Isolate* isolate, Local<v8::Value> obj);
2025-10-31T06:50:57.606933021Z npm error       |     ^~~~~~~~~
2025-10-31T06:50:57.606934731Z npm error /opt/render/.cache/25.1.0/include/node/v8-primitive.h:649:50: note:   no known conversion for argument 2 from ‘Local<v8::String>’ to ‘Local<v8::Value>’
2025-10-31T06:50:57.606936441Z npm error   649 |     Utf8Value(Isolate* isolate, Local<v8::Value> obj);
2025-10-31T06:50:57.606938111Z npm error       |                                 ~~~~~~~~~~~~~~~~~^~~
2025-10-31T06:50:57.606939761Z npm error ./src/util/data.lzz: In function ‘void Data::ResultValueFromJS(v8::Isolate*, sqlite3_context*, v8::Local<v8::Value>, DataConverter*)’:
2025-10-31T06:50:57.606941431Z npm error ./src/util/data.lzz:141:452: error: no matching function for call to ‘v8::String::Utf8Value::Utf8Value(v8::Isolate*&, v8::Local<v8::String>)’
2025-10-31T06:50:57.606943172Z npm error /opt/render/.cache/25.1.0/include/node/v8-primitive.h:649:5: note: candidate: ‘v8::String::Utf8Value::Utf8Value(v8::Isolate*, v8::Local<v8::Value>)’
2025-10-31T06:50:57.606944872Z npm error   649 |     Utf8Value(Isolate* isolate, Local<v8::Value> obj);
2025-10-31T06:50:57.606946582Z npm error       |     ^~~~~~~~~
2025-10-31T06:50:57.606948292Z npm error /opt/render/.cache/25.1.0/include/node/v8-primitive.h:649:50: note:   no known conversion for argument 2 from ‘Local<v8::String>’ to ‘Local<v8::Value>’
2025-10-31T06:50:57.606949972Z npm error   649 |     Utf8Value(Isolate* isolate, Local<v8::Value> obj);
2025-10-31T06:50:57.606951632Z npm error       |                                 ~~~~~~~~~~~~~~~~~^~~
2025-10-31T06:50:57.606953332Z npm error ./src/util/binder.lzz: In member function ‘int Binder::BindObject(v8::Isolate*, v8::Local<v8::Object>, Statement*)’:
2025-10-31T06:50:57.606955063Z npm error ./src/util/binder.lzz:126:75: error: no matching function for call to ‘v8::Object::HasOwnProperty(v8::Local<v8::Context>&, v8::Local<v8::String>&)’
2025-10-31T06:50:57.606956763Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:677:37: note: candidate: ‘v8::Maybe<bool> v8::Object::HasOwnProperty(v8::Local<v8::Context>, v8::Local<v8::Name>)’
2025-10-31T06:50:57.606958503Z npm error   677 |   V8_WARN_UNUSED_RESULT Maybe<bool> HasOwnProperty(Local<Context> context,
2025-10-31T06:50:57.606960193Z npm error       |                                     ^~~~~~~~~~~~~~
2025-10-31T06:50:57.606961873Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:678:64: note:   no known conversion for argument 2 from ‘Local<v8::String>’ to ‘Local<v8::Name>’
2025-10-31T06:50:57.606963543Z npm error   678 |                                                    Local<Name> key);
2025-10-31T06:50:57.606965304Z npm error       |                                                    ~~~~~~~~~~~~^~~
2025-10-31T06:50:57.606971234Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:679:37: note: candidate: ‘v8::Maybe<bool> v8::Object::HasOwnProperty(v8::Local<v8::Context>, uint32_t)’
2025-10-31T06:50:57.606973044Z npm error   679 |   V8_WARN_UNUSED_RESULT Maybe<bool> HasOwnProperty(Local<Context> context,
2025-10-31T06:50:57.606974744Z npm error       |                                     ^~~~~~~~~~~~~~
2025-10-31T06:50:57.606976494Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:680:61: note:   no known conversion for argument 2 from ‘v8::Local<v8::String>’ to ‘uint32_t’ {aka ‘unsigned int’}
2025-10-31T06:50:57.606978185Z npm error   680 |                                                    uint32_t index);
2025-10-31T06:50:57.606979875Z npm error       |                                                    ~~~~~~~~~^~~~~
2025-10-31T06:50:57.606981595Z npm error ./src/util/binder.lzz:132:78: error: no matching function for call to ‘v8::String::Utf8Value::Utf8Value(v8::Isolate*&, v8::Local<v8::String>&)’
2025-10-31T06:50:57.606986165Z npm error /opt/render/.cache/25.1.0/include/node/v8-primitive.h:649:5: note: candidate: ‘v8::String::Utf8Value::Utf8Value(v8::Isolate*, v8::Local<v8::Value>)’
2025-10-31T06:50:57.606987885Z npm error   649 |     Utf8Value(Isolate* isolate, Local<v8::Value> obj);
2025-10-31T06:50:57.606989565Z npm error       |     ^~~~~~~~~
2025-10-31T06:50:57.606991295Z npm error /opt/render/.cache/25.1.0/include/node/v8-primitive.h:649:50: note:   no known conversion for argument 2 from ‘Local<v8::String>’ to ‘Local<v8::Value>’
2025-10-31T06:50:57.606992956Z npm error   649 |     Utf8Value(Isolate* isolate, Local<v8::Value> obj);
2025-10-31T06:50:57.606994666Z npm error       |                                 ~~~~~~~~~~~~~~~~~^~~
2025-10-31T06:50:57.606996396Z npm error ./src/util/binder.lzz:138:72: error: no matching function for call to ‘v8::Object::Get(v8::Local<v8::Context>&, v8::Local<v8::String>&)’
2025-10-31T06:50:57.606998126Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:307:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)’
2025-10-31T06:50:57.606999806Z npm error   307 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
2025-10-31T06:50:57.607001566Z npm error       |                                           ^~~
2025-10-31T06:50:57.607003247Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:308:60: note:   no known conversion for argument 2 from ‘Local<v8::String>’ to ‘Local<v8::Value>’
2025-10-31T06:50:57.607004957Z npm error   308 |                                               Local<Value> key);
2025-10-31T06:50:57.607006847Z npm error       |                                               ~~~~~~~~~~~~~^~~
2025-10-31T06:50:57.607008687Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:309:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::MaybeLocal<v8::Object>)’
2025-10-31T06:50:57.607011527Z npm error   309 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
2025-10-31T06:50:57.607013237Z npm error       |                                           ^~~
2025-10-31T06:50:57.607014937Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:309:43: note:   candidate expects 3 arguments, 2 provided
2025-10-31T06:50:57.607016648Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:313:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)’
2025-10-31T06:50:57.607018378Z npm error   313 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
2025-10-31T06:50:57.607020118Z npm error       |                                           ^~~
2025-10-31T06:50:57.607021768Z npm error /opt/render/.cache/25.1.0/include/node/v8-object.h:314:56: note:   no known conversion for argument 2 from ‘v8::Local<v8::String>’ to ‘uint32_t’ {aka ‘unsigned int’}
2025-10-31T06:50:57.607023448Z npm error   314 |                                               uint32_t index);
2025-10-31T06:50:57.607025128Z npm error       |                                               ~~~~~~~~~^~~~~
2025-10-31T06:50:57.607026918Z npm error ./src/better_sqlite3.lzz: In static member function ‘static void Addon::JS_setErrorConstructor(const v8::FunctionCallbackInfo<v8::Value>&)’:
2025-10-31T06:50:57.607028649Z npm error ./src/better_sqlite3.lzz:37:104: error: ‘struct Addon’ has no member named ‘SqliteError’
2025-10-31T06:50:57.607030319Z npm error In file included from /opt/render/.cache/25.1.0/include/node/v8-isolate.h:22,
2025-10-31T06:50:57.607032009Z npm error                  from /opt/render/.cache/25.1.0/include/node/v8-snapshot.h:9,
2025-10-31T06:50:57.607036259Z npm error                  from /opt/render/.cache/25.1.0/include/node/v8-context.h:15:
2025-10-31T06:50:57.60704396Z npm error /opt/render/.cache/25.1.0/include/node/v8-function-callback.h: In instantiation of ‘v8::Local<v8::Value> v8::FunctionCallbackInfo<F>::operator[](int) const [with T = v8::Value]’:
2025-10-31T06:50:57.60704582Z npm error ./src/objects/database.lzz:151:63:   required from here
2025-10-31T06:50:57.60704786Z npm error /opt/render/.cache/25.1.0/include/node/v8-function-callback.h:623:47: error: could not convert ‘v8::Undefined(((const v8::FunctionCallbackInfo<v8::Value>*)this)->v8::FunctionCallbackInfo<v8::Value>::GetIsolate())’ from ‘Local<v8::Primitive>’ to ‘Local<v8::Value>’
2025-10-31T06:50:57.60704958Z npm error   623 |   if (i < 0 || Length() <= i) return Undefined(GetIsolate());
2025-10-31T06:50:57.60705127Z npm error       |                                      ~~~~~~~~~^~~~~~~~~~~~~~
2025-10-31T06:50:57.60705294Z npm error       |                                               |
2025-10-31T06:50:57.607054631Z npm error       |                                               Local<v8::Primitive>
2025-10-31T06:50:57.607056291Z npm error make: *** [better_sqlite3.target.mk:122: Release/obj.target/better_sqlite3/src/better_sqlite3.o] Error 1
2025-10-31T06:50:57.607057981Z npm error gyp ERR! build error 
2025-10-31T06:50:57.607059671Z npm error gyp ERR! stack Error: `make` failed with exit code: 2
2025-10-31T06:50:57.607061391Z npm error gyp ERR! stack at ChildProcess.<anonymous> (/opt/render/project/nodes/node-25.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:219:23)
2025-10-31T06:50:57.607063081Z npm error gyp ERR! System Linux 6.8.0-1041-aws
2025-10-31T06:50:57.607064781Z npm error gyp ERR! command "/opt/render/project/nodes/node-25.1.0/bin/node" "/opt/render/project/nodes/node-25.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
2025-10-31T06:50:57.607067362Z npm error gyp ERR! cwd /opt/render/project/src/node_modules/better-sqlite3
2025-10-31T06:50:57.607069072Z npm error gyp ERR! node -v v25.1.0
2025-10-31T06:50:57.607070752Z npm error gyp ERR! node-gyp -v v11.4.2
2025-10-31T06:50:57.607072432Z npm error gyp ERR! not ok
2025-10-31T06:50:57.607074112Z npm error A complete log of this run can be found in: /opt/render/.cache/_logs/2025-10-31T06_49_28_726Z-debug-0.log
2025-10-31T06:50:57.749057503Z ==> Build failed 😞
2025-10-31T06:50:57.749075715Z ==> Common ways to troubleshoot your deploy: https://render.com/docs/troubleshooting-deploys